### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jmadden91** [heytensai/rpi-power-monitor-mqtt#1]
Hey mate, 

Thank you very much for your work with this script.

Just a few suggestions for improvements to help a novice like me get it working. Firstly maybe just a note in the readme to first install/check installed the two packages required:

- apt-get install influxdb-client
- apt-get install mosquitto-clients

Secondly, I have a username and password set for my mosquitto broker, so had to add a -u "username" and -P "password" variable. Would it be possible to declare the variables at the start of the script like you do with the "server" and "prefix"?

Cheers
Jake

**Comment by emersonsc** [comment]
> Hey mate,
> 
> Thank you very much for your work with this script.
> 
> Just a few suggestions for improvements to help a novice like me get it working. Firstly maybe just a note in the readme to first install/check installed the two packages required:
> 
> * apt-get install influxdb-client
> * apt-get install mosquitto-clients
> 
> Secondly, I have a username and password set for my mosquitto broker, so had to add a -u "username" and -P "password" variable. Would it be possible to declare the variables at the start of the script like you do with the "server" and "prefix"?
> 
> Cheers Jake

Could you give me some pointers on how to install this? I get the installing the prerequisites, but after that it gives a cron-tab example, nothing else. What do I do with the powermon-mqtt.sh file? Where do I put in my MQTT server ip and port? The password?
