### ISSUE TITLE
Installing 

### ISSUE THREAD

**Issue by emersonsc** [heytensai/rpi-power-monitor-mqtt#6]
I'm a bit confused. After I install the prerequisites, how do I install the script? I'm looking to buy the RPI power monitor and it directs you to here to implement MQTT for home assistant use but I don't get how to install this

**Comment by heytensai** [comment]
Copy the powermon-mqtt.sh script to the /home/pi directory on your power-monitor RPI and make it executable.

You can test it from the command line. You'll need to give the IP address of your MQTT broker, which is commonly the same as your HA server.

[pi@powermon ~]$ ./powermon-mqtt.sh 10.42.42.19

One way to verify that it worked is by watching the MQTT data using mosquitto_sub. You should see something like this:

[homeassistant@ha ~]$ mosquitto_sub -v -t 'powermon/#'
powermon/ct_1/power 1436.3
powermon/ct_2/power 1740.9
powermon/ct_3/power 1.2
powermon/ct_4/power 0
powermon/ct_5/power 0
powermon/ct_6/power 472.7

If that works then you're ready to add the cron tab and add entities in HA.

**Comment by emersonsc** [comment]
> Copy the powermon-mqtt.sh script to the /home/pi directory on your power-monitor RPI and make it executable.
> 
> You can test it from the command line. You'll need to give the IP address of your MQTT broker, which is commonly the same as your HA server.
> 
> [pi@powermon ~]$ ./powermon-mqtt.sh 10.42.42.19
> 
> One way to verify that it worked is by watching the MQTT data using mosquitto_sub. You should see something like this:
> 
> [homeassistant@ha ~]$ mosquitto_sub -v -t 'powermon/#' powermon/ct_1/power 1436.3 powermon/ct_2/power 1740.9 powermon/ct_3/power 1.2 powermon/ct_4/power 0 powermon/ct_5/power 0 powermon/ct_6/power 472.7
> 
> If that works then you're ready to add the cron tab and add entities in HA.

Sorry for my ignorance, this is a whole new venture for me.
Adding entities is simple, I know how to do that.

What I dont know anything about is cron tab. Is that something within the interface for the Power Monitor i would access through my browser?

Also, is there a need to specify the port? I never changed mine, its the default that MosquittoMQTT sets up on its own. I figured out how to add the username and password so thats no an issue.

Also, once I copy it into the directory you mentioned, how to I make it executable?

Lastly, if the Pi needs to be restarted for any reason, will i need to re-execute it, or will it do that on its own?

**Comment by heytensai** [comment]
> Sorry for my ignorance, this is a whole new venture for me.

Everybody starts somewhere. Not a problem.

> What I dont know anything about is cron tab.

Cron is a way to schedule tasks to run on a repeating schedule. It's a service provided by Linux itself, not by power-monitor per se. To install a crontab, as user "pi" run the command "crontab -e" and then paste in that snippet I provided. Save and exit. Cron will start up on reboot, so nothing else needs to be done.

This page is a more in-depth explanation of cron: https://www.cyberciti.biz/faq/how-do-i-add-jobs-to-cron-under-linux-or-unix-oses/

> Also, is there a need to specify the port?

I didn't add support for different ports. The script will assume the default.

> Also, once I copy it into the directory you mentioned, how to I make it executable?

chmod 755 powermon-mqtt.sh

**Comment by emersonsc** [comment]
> > Sorry for my ignorance, this is a whole new venture for me.
> 
> Everybody starts somewhere. Not a problem.
> 
> > What I dont know anything about is cron tab.
> 
> Cron is a way to schedule tasks to run on a repeating schedule. It's a service provided by Linux itself, not by power-monitor per se. To install a crontab, as user "pi" run the command "crontab -e" and then paste in that snippet I provided. Save and exit. Cron will start up on reboot, so nothing else needs to be done.
> 
> This page is a more in-depth explanation of cron: https://www.cyberciti.biz/faq/how-do-i-add-jobs-to-cron-under-linux-or-unix-oses/
> 
> > Also, is there a need to specify the port?
> 
> I didn't add support for different ports. The script will assume the default.
> 
> > Also, once I copy it into the directory you mentioned, how to I make it executable?
> 
> chmod 755 powermon-mqtt.sh

so since Ill be running two of these (my shop has its own drop and meter from the pole), I would enter the prefix this way?

Shop Unit: ./powermon-mqtt.sh 192.168.50.22 Shop
House Unit: ./powermon-mqtt.sh 192.168.50.22 House

Would this put Shop or Home before the topic, ie:
Shop/powermon/ct_1/power 1436.3
Shop/powermon/ct_2/power 1740.9
Shop/powermon/ct_3/power 1.2
Shop/powermon/ct_4/power 0
Shop/powermon/ct_5/power 0
Shop/powermon/ct_6/power 472.7

Also, could I do this with the code instead of putting the information in when start the script.

#!/bin/bash

[ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -en "$0" "$0" "$@" || :

HOST="192.168.50.22"
PREFIX="Shop"


MQTT_UN=""
MQTT_PW=""

for ct in $(seq 0 5)
do
	w=$(influx -database power_monitor -execute "select mean(power) from raw_cts where ct = '${ct}' and time > now() - 1m group by power fill(0) limit 1" -format csv |grep ^raw_cts |perl -lpe 's/.*,//; s/(\..).*/$1/; $_=0 if ($_<0);')
	mosquitto_pub -u "${MQTT_UN}" -P "${MQTT_PW}" -h "${HOST}" -t "${PREFIX}/ct_${ct}/power" -m "${w}"
done

homeload=$(influx -database power_monitor -execute "select mean(power) from home_load where time > now() - 1m group by power fill(0) limit 1" -format csv |grep ^home_load |perl -lpe 's/.*,//; s/(\..).*/$1/')
mosquitto_pub -u "${MQTT_UN}" -P "${MQTT_PW}" -h "${HOST}" -t "${PREFIX}/home_load/power" -m "${homeload}"

**Comment by heytensai** [comment]
That's all correct, except that "powermon" is not included in the prefix automatically. So your topic would just be "Shop/ct_1/power" or "Home/ct_1/power", etc.

**Comment by emersonsc** [comment]
> That's all correct, except that "powermon" is not included in the prefix automatically. So your topic would just be "Shop/ct_1/power" or "Home/ct_1/power", etc.

Oh even better. Perfect thank you so much for the help AND this script to make this project Home Assistant friendly. Now I have to patiently wait for my kits to ship and get here!

**Comment by emersonsc** [comment]
I have got everything up and going. I can listen to all of them in the MQTT Integration screen. They all show up as sensors. A couple issues i have how ever:

CT6 errors when trying to add a card saying "Entity is non-numeric", and does not show a value when manually listening to it. It DOES show up as a sensor how ever.

When trying to add the sensors to the energy dashboard, none of them CTs show up as available energy sensors.

Lasty, when I added the sensor for grid consumption, I have this error show up on the Energy Dashboard setup:
Unexpected device class
The following entities do not have the expected device class:
sensor.shop_energy_spent

**Comment by emersonsc** [comment]
mqtt:
  sensor:
    - name: "Weather Station"
      state_topic: "raspberry/ws/status"
      json_attributes_topic: "raspberry/ws/sensors"
      
    - name: "Shop Main 1"
      state_topic: "Shop/ct_1/power"
      state_class: measurement
      device_class: power
      icon: mdi:electron-framework
      unit_of_measurement: 'W'
 
    - name: "Shop Main 2"
      state_topic: "Shop/ct_2/power"
      state_class: measurement
      device_class: power
      icon: mdi:electron-framework
      unit_of_measurement: 'W'
      
    - name: "Plasma Cutter"
      state_topic: "Shop/ct_3/power"
      state_class: measurement
      device_class: power
      icon: mdi:electron-framework
      unit_of_measurement: 'W'
      
    - name: "Air Compressor"
      state_topic: "Shop/ct_4/power"
      state_class: measurement
      device_class: power
      icon: mdi:electron-framework
      unit_of_measurement: 'W'
      
    - name: "Sarah's Bench"
      state_topic: "Shop/ct_5/power"
      state_class: measurement
      device_class: power
      icon: mdi:electron-framework
      unit_of_measurement: 'W'
      
    - name: "Server Plug"
      state_topic: "Shop/ct_6/power"
      state_class: measurement
      device_class: power
      icon: mdi:electron-framework
      unit_of_measurement: 'W'
      
    - name: "Shop Power"
      state_topic: "Shop/home_load/power"
      state_class: measurement
      device_class: power
      icon: mdi:electron-framework
      unit_of_measurement: 'W'

**Comment by emersonsc** [comment]
> I have got everything up and going. I can listen to all of them in the MQTT Integration screen. They all show up as sensors. A couple issues i have how ever:
> 
> CT6 errors when trying to add a card saying "Entity is non-numeric", and does not show a value when manually listening to it. It DOES show up as a sensor how ever.
> 
> When trying to add the sensors to the energy dashboard, none of them CTs show up as available energy sensors.
> 
> Lasty, when I added the sensor for grid consumption, I have this error show up on the Energy Dashboard setup: Unexpected device class The following entities do not have the expected device class: sensor.shop_energy_spent

This issue is caused by the code being set up for v0.1.0. David has since changed the CT values from 0-5 to 1-6 in v0.2.0. I put in a pull request to update the code #8
