### ISSUE TITLE
Code Using old Channel Numbers

### ISSUE THREAD

**Issue by emersonsc** [heytensai/rpi-power-monitor-mqtt#7]
I dont know how to do pull requests, so I am putting it here instead.

the code on line 12 needs to be changed from 
for ct in $(seq 0 5)

to
for ct in $(seq 1 6)

with release [https://github.com/David00/rpi-power-monitor/releases/tag/v0.2.0](url) the channel numbers were changed from 0-5 to 1-6.

**Comment by emersonsc** [comment]
#8

**Comment by heytensai** [comment]
I appreciate your feedback and pull request. I haven't had a lot of time to work on this lately, but I will merge your changes in shortly.

**Comment by heytensai** [comment]
I tagged the wrong issue in the commit :(
This was merged in bdc8ff6042596979f52b6b417723f4b68544b208

**Comment by emersonsc** [comment]
No worries I figured as much. Work is slow for me at the moment so I've had time to tinker, then I felt like a was bugging so I closed it all.
